### ISSUE TITLE
StationID

### ISSUE THREAD

**Issue by Wizi309** [yo-less/MMM-nextbike#5]
Hey,

How can I get the Station and City ID?

Open your web browser and navigate to the nextbike API result page. -->it does not work

**Comment by yo-less** [comment]
It works without a hitch on my end. Try a different browser, I just opened it in Firefox and could easily access all the data.

**Comment by Wizi309** [comment]
Solved thanks

**Comment by yo-less** [comment]
You're welcome, enjoy your rides 😋
